// skill list
export const skills = [
  "React.js, Next.js, and modern frontend architecture",
  "State management with Redux Toolkit and scalable patterns",
  "JavaScript (ES6+) and TypeScript for robust application development",
  "Building responsive, high-performance UIs with Tailwind CSS",
  "Backend development using Node.js, Express.js, and NestJS",
  "Designing and consuming GraphQL and RESTful APIs",
  "Database design and optimization with MongoDB and PostgreSQL",
  "ORM and data modeling using Prisma",
  "Real-time application development with Socket.IO and WebRTC",
  "API design, system architecture, and scalable microservices patterns",
  "Authentication & authorization (JWT, OAuth)",
  "Performance optimization, caching strategies, and system scalability",
  "CI/CD pipelines, DevOps practices, and deployment automation",
  "AI/ML integration, prompt engineering, and intelligent system development",
  "Mobile app development with React Native and cross-platform solutions",
  "Cloud platforms (AWS, Azure, GCP) and serverless architectures",
  "Testing strategies (unit, integration, E2E) and quality assurance",
  "Agile methodologies, Scrum, and modern development workflows",
  "Technical leadership, team collaboration, and project mentorship",
];
